# Generated by Django 5.2.8 on 2025-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Languages', 'Programming Languages'), ('Backend', 'Backend Frameworks/Libraries'), ('Frontend', 'Frontend Development/UI'), ('Database', 'Databases & ORMs'), ('Tools', 'Tools, DevOps & OS'), ('Concepts', 'Core Concepts')], default='Languages', help_text='Select the category this skill belongs to.', max_length=10),
        ),
    ]
