# Generated by Django 5.2.8 on 2025-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_skill_options_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Language', 'Programming Languages'), ('Backend', 'Backend Frameworks/Libraries'), ('Frontend', 'Frontend Development/UI'), ('Database', 'Databases & ORMs'), ('Tools', 'Tools, DevOps & OS'), ('Concepts', 'Core Concepts')], default='Language', help_text='Select the category this skill belongs to.', max_length=10),
        ),
    ]
