# Generated by Django 5.2.6 on 2025-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_profile_language_interest_experience_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='experience',
            name='points',
            field=models.TextField(help_text='Points separated by newlines'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Language', 'Programming Languages'), ('Backend', 'Backend Frameworks/Libraries'), ('Frontend', 'Frontend Development/UI'), ('Database', 'Databases & ORMs'), ('Tools', 'Tools, DevOps & OS'), ('Concepts', 'Core Concepts')], default='Language', max_length=10),
        ),
    ]
