# Generated by Django 5.2.6 on 2025-11-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_contactmessage_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-is_current', '-id']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['lang']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'order', '-id']},
        ),
        migrations.AddField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, help_text='Organization that issued the certification', max_length=200),
        ),
        migrations.AddField(
            model_name='certification',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if this is your current position'),
        ),
        migrations.AddField(
            model_name='interest',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional: emoji or icon', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Display as featured project'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
    ]
